version: '3.8'

services:

  web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "${API_PORT}:8000"
      env_file:
        - .env      
      restart: on-failure
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_REGION_NAME}